#!/bin/bash
# siat-gh-issue.sh - Create GitHub issue from spec document
# Deterministic issue creation with consistent formatting
#
# Usage: siat-gh-issue.sh <spec_path> [--dry-run]
# Output: JSON with issue URL or dry-run preview

set -e

SPEC_PATH="$1"
DRY_RUN=false
[[ "$2" == "--dry-run" ]] && DRY_RUN=true

# ============================================================================
# Helper Functions
# ============================================================================

slugify_to_title() {
    # task-id-name → Task Id Name
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

get_frontmatter_field() {
    local file="$1"
    local field="$2"

    awk -v field="$field" '
        /^---$/ { if (in_fm) exit; in_fm=1; next }
        in_fm && $0 ~ "^"field":" {
            gsub(/^[^:]+:[[:space:]]*/, "")
            gsub(/^"/, ""); gsub(/"$/, "")
            print
            exit
        }
    ' "$file"
}

get_section() {
    local file="$1"
    local header="$2"

    awk -v header="$header" '
        /^---$/ { if (!past_fm) { past_fm=1; next } }
        past_fm && $0 ~ "^##[[:space:]]+"header {
            in_section=1
            next
        }
        in_section && /^##[[:space:]]/ { exit }
        in_section { print }
    ' "$file" | sed '/^$/N;/^\n$/d'  # Remove consecutive blank lines
}

get_body_after_frontmatter() {
    local file="$1"
    awk '
        /^---$/ { if (in_fm) { in_fm=0; next } in_fm=1; next }
        !in_fm { print }
    ' "$file"
}

# ============================================================================
# Main Logic
# ============================================================================

if [[ ! -f "$SPEC_PATH" ]]; then
    echo '{"error": "spec file not found", "path": "'"$SPEC_PATH"'"}' | jq .
    exit 1
fi

# Extract metadata
TASK_ID=$(get_frontmatter_field "$SPEC_PATH" "id")
STEP=$(basename "$SPEC_PATH" .md)

# Generate title
TITLE=$(slugify_to_title "$TASK_ID")
TITLE="[${STEP}] ${TITLE}"

# Extract key sections for body
SUMMARY=$(get_section "$SPEC_PATH" "Summary\|요약\|Overview\|개요")
REQUIREMENTS=$(get_section "$SPEC_PATH" "Requirements\|요구사항\|Scope\|범위")
ACCEPTANCE=$(get_section "$SPEC_PATH" "Acceptance\|인수 조건\|Done\|완료 조건")

# Build issue body
BODY="## Source
- Spec: \`${SPEC_PATH}\`
- Task ID: \`${TASK_ID}\`
- Step: \`${STEP}\`

---

"

if [[ -n "$SUMMARY" ]]; then
    BODY+="## Summary
${SUMMARY}

"
fi

if [[ -n "$REQUIREMENTS" ]]; then
    BODY+="## Requirements
${REQUIREMENTS}

"
fi

if [[ -n "$ACCEPTANCE" ]]; then
    BODY+="## Acceptance Criteria
${ACCEPTANCE}

"
fi

BODY+="---
*Generated by siat workflow*"

# Labels based on step
LABELS=""
case "$STEP" in
    clarify|prd)
        LABELS="documentation"
        ;;
    design|visual-design)
        LABELS="design"
        ;;
    implement)
        LABELS="enhancement"
        ;;
    fix|reproduce|root-cause)
        LABELS="bug"
        ;;
    verify)
        LABELS="testing"
        ;;
esac

if [[ "$DRY_RUN" == "true" ]]; then
    jq -n \
        --arg title "$TITLE" \
        --arg body "$BODY" \
        --arg labels "$LABELS" \
        --arg spec_path "$SPEC_PATH" \
        '{
            dry_run: true,
            title: $title,
            body: $body,
            labels: $labels,
            spec_path: $spec_path
        }'
    exit 0
fi

# Create issue
ISSUE_URL=$(gh issue create \
    --title "$TITLE" \
    --body "$BODY" \
    ${LABELS:+--label "$LABELS"} \
    2>&1)

ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -o '[0-9]*$')

# Append issue link to spec
if [[ -n "$ISSUE_NUMBER" ]]; then
    # Add to frontmatter
    sed -i '' "s/^---$/---\ngithub_issue: \"${ISSUE_URL}\"/" "$SPEC_PATH" 2>/dev/null || \
    sed -i "s/^---$/---\ngithub_issue: \"${ISSUE_URL}\"/" "$SPEC_PATH"
fi

jq -n \
    --arg url "$ISSUE_URL" \
    --arg number "$ISSUE_NUMBER" \
    --arg title "$TITLE" \
    --arg spec_path "$SPEC_PATH" \
    '{
        success: true,
        issue_url: $url,
        issue_number: $number,
        title: $title,
        spec_path: $spec_path
    }'
