#!/bin/bash
# siat-gh-issue.sh - Create GitHub issue from spec document
# Deterministic issue creation with consistent formatting
#
# Usage: siat-gh-issue.sh <spec_path> [--dry-run]
# Environment:
#   SIAT_REMOTE=true (required to enable this script)
# Output: JSON with issue URL or dry-run preview

set -e

# Skip if not in remote mode
if [[ "${SIAT_REMOTE}" != "true" ]]; then
    echo '{"skipped": true, "reason": "SIAT_REMOTE not enabled"}' | jq .
    exit 0
fi

SPEC_PATH="$1"
DRY_RUN=false
[[ "$2" == "--dry-run" ]] && DRY_RUN=true

# ============================================================================
# Helper Functions
# ============================================================================

slugify_to_title() {
    # task-id-name → Task Id Name
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

get_frontmatter_field() {
    local file="$1"
    local field="$2"

    awk -v field="$field" '
        /^---$/ { if (in_fm) exit; in_fm=1; next }
        in_fm && $0 ~ "^"field":" {
            gsub(/^[^:]+:[[:space:]]*/, "")
            gsub(/^"/, ""); gsub(/"$/, "")
            print
            exit
        }
    ' "$file"
}

get_section() {
    local file="$1"
    local header="$2"

    awk -v header="$header" '
        /^---$/ { if (!past_fm) { past_fm=1; next } }
        past_fm && $0 ~ "^##[[:space:]]+"header {
            in_section=1
            next
        }
        in_section && /^##[[:space:]]/ { exit }
        in_section { print }
    ' "$file" | sed '/^$/N;/^\n$/d'  # Remove consecutive blank lines
}

get_body_after_frontmatter() {
    local file="$1"
    awk '
        /^---$/ { if (in_fm) { in_fm=0; next } in_fm=1; next }
        !in_fm { print }
    ' "$file"
}

# ============================================================================
# Main Logic
# ============================================================================

if [[ ! -f "$SPEC_PATH" ]]; then
    echo '{"error": "spec file not found", "path": "'"$SPEC_PATH"'"}' | jq .
    exit 1
fi

# Extract metadata
TASK_ID=$(get_frontmatter_field "$SPEC_PATH" "id")
STEP=$(basename "$SPEC_PATH" .md)

# Generate title
TITLE=$(slugify_to_title "$TASK_ID")
TITLE="[${STEP}] ${TITLE}"

# Get full spec content (after frontmatter)
FULL_SPEC=$(get_body_after_frontmatter "$SPEC_PATH")

# Build issue body
BODY="## Source
- Spec: \`${SPEC_PATH}\`
- Task ID: \`${TASK_ID}\`
- Step: \`${STEP}\`

---

<details>
<summary>📄 <strong>Full Spec Document</strong> (click to expand)</summary>

${FULL_SPEC}

</details>

---
*Generated by siat workflow*"

# Label is the step name
LABELS="$STEP"

if [[ "$DRY_RUN" == "true" ]]; then
    jq -n \
        --arg title "$TITLE" \
        --arg body "$BODY" \
        --arg labels "$LABELS" \
        --arg spec_path "$SPEC_PATH" \
        '{
            dry_run: true,
            title: $title,
            body: $body,
            labels: $labels,
            spec_path: $spec_path
        }'
    exit 0
fi

# Create issue
ISSUE_URL=$(gh issue create \
    --title "$TITLE" \
    --body "$BODY" \
    ${LABELS:+--label "$LABELS"} \
    2>&1)

ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -o '[0-9]*$')

# Append issue link to spec
if [[ -n "$ISSUE_NUMBER" ]]; then
    # Add github_issue field after first --- in frontmatter
    # Use awk for cross-platform compatibility
    awk -v issue_url="$ISSUE_URL" '
        NR==1 && /^---$/ { print; print "github_issue: \"" issue_url "\""; next }
        { print }
    ' "$SPEC_PATH" > "${SPEC_PATH}.tmp" && mv "${SPEC_PATH}.tmp" "$SPEC_PATH"
fi

jq -n \
    --arg url "$ISSUE_URL" \
    --arg number "$ISSUE_NUMBER" \
    --arg title "$TITLE" \
    --arg spec_path "$SPEC_PATH" \
    '{
        success: true,
        issue_url: $url,
        issue_number: $number,
        title: $title,
        spec_path: $spec_path
    }'
