#!/bin/bash
# siat-gh-pr.sh - Create GitHub PR from completed workflow
# Deterministic PR creation with spec-based content
#
# Usage: siat-gh-pr.sh <task_dir> [--dry-run] [--force]
# Flags:
#   --dry-run  Preview without creating PR
#   --force    Skip SIAT_REMOTE check (for manual invocation)
# Environment:
#   SIAT_REMOTE=true (auto-enabled in remote mode)
# Output: JSON with PR URL or dry-run preview

set -e

# Parse arguments
TASK_DIR=""
DRY_RUN=false
FORCE=false

for arg in "$@"; do
    case $arg in
        --dry-run) DRY_RUN=true ;;
        --force) FORCE=true ;;
        *) [[ -z "$TASK_DIR" ]] && TASK_DIR="$arg" ;;
    esac
done

# Skip if not in remote mode (unless forced)
if [[ "${SIAT_REMOTE}" != "true" && "$FORCE" != "true" ]]; then
    echo '{"skipped": true, "reason": "SIAT_REMOTE not enabled. Use --force to override."}' | jq .
    exit 0
fi

# ============================================================================
# Helper Functions
# ============================================================================

slugify_to_title() {
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

get_frontmatter_field() {
    local file="$1"
    local field="$2"

    awk -v field="$field" '
        /^---$/ { if (in_fm) exit; in_fm=1; next }
        in_fm && $0 ~ "^"field":" {
            gsub(/^[^:]+:[[:space:]]*/, "")
            gsub(/^"/, ""); gsub(/"$/, "")
            print
            exit
        }
    ' "$file"
}

get_section() {
    local file="$1"
    local header="$2"

    awk -v header="$header" '
        /^---$/ { if (!past_fm) { past_fm=1; next } }
        past_fm && $0 ~ "^##[[:space:]]+"header {
            in_section=1
            next
        }
        in_section && /^##[[:space:]]/ { exit }
        in_section { print }
    ' "$file" | sed '/^$/N;/^\n$/d'
}

# ============================================================================
# Main Logic
# ============================================================================

if [[ ! -d "$TASK_DIR" ]]; then
    echo '{"error": "task directory not found", "path": "'"$TASK_DIR"'"}' | jq .
    exit 1
fi

# Get task ID from directory name
TASK_ID=$(basename "$TASK_DIR")

# Find relevant specs
IMPLEMENT_SPEC="${TASK_DIR}/implement.md"
DESIGN_SPEC="${TASK_DIR}/design.md"
PRD_SPEC="${TASK_DIR}/prd.md"
CLARIFY_SPEC="${TASK_DIR}/clarify.md"

# Check implement spec exists
if [[ ! -f "$IMPLEMENT_SPEC" ]]; then
    echo '{"error": "implement.md not found", "task_dir": "'"$TASK_DIR"'"}' | jq .
    exit 1
fi

# Generate PR title
TITLE=$(slugify_to_title "$TASK_ID")
TITLE="feat: ${TITLE}"

# Build PR body from specs
BODY="## Summary

"

# From clarify/prd
if [[ -f "$PRD_SPEC" ]]; then
    SUMMARY=$(get_section "$PRD_SPEC" "Summary\|요약\|Overview\|개요")
    [[ -n "$SUMMARY" ]] && BODY+="${SUMMARY}

"
elif [[ -f "$CLARIFY_SPEC" ]]; then
    SUMMARY=$(get_section "$CLARIFY_SPEC" "Summary\|요약\|핵심")
    [[ -n "$SUMMARY" ]] && BODY+="${SUMMARY}

"
fi

# Changes from implement
CHANGES=$(get_section "$IMPLEMENT_SPEC" "Changes\|변경\|Implementation\|구현")
if [[ -n "$CHANGES" ]]; then
    BODY+="## Changes

${CHANGES}

"
fi

# From design
if [[ -f "$DESIGN_SPEC" ]]; then
    ARCH=$(get_section "$DESIGN_SPEC" "Architecture\|아키텍처\|Structure\|구조")
    if [[ -n "$ARCH" ]]; then
        BODY+="## Architecture

${ARCH}

"
    fi
fi

# Test plan from implement
TEST_PLAN=$(get_section "$IMPLEMENT_SPEC" "Test\|테스트\|Verification\|검증")
if [[ -n "$TEST_PLAN" ]]; then
    BODY+="## Test Plan

${TEST_PLAN}

"
fi

# Related specs
BODY+="## Related Specs

"
for spec in "$CLARIFY_SPEC" "$PRD_SPEC" "$DESIGN_SPEC" "$IMPLEMENT_SPEC"; do
    if [[ -f "$spec" ]]; then
        BODY+="- \`$(basename "$spec")\`
"
    fi
done

# Related issues
BODY+="
## Related Issues

"
for spec in "$CLARIFY_SPEC" "$PRD_SPEC" "$DESIGN_SPEC"; do
    if [[ -f "$spec" ]]; then
        ISSUE_URL=$(get_frontmatter_field "$spec" "github_issue")
        if [[ -n "$ISSUE_URL" ]]; then
            ISSUE_NUM=$(echo "$ISSUE_URL" | grep -o '[0-9]*$')
            BODY+="- Closes #${ISSUE_NUM}
"
        fi
    fi
done

BODY+="
---
*Generated by siat workflow*"

# Branch name
BRANCH_NAME="feat/${TASK_ID}"

if [[ "$DRY_RUN" == "true" ]]; then
    jq -n \
        --arg title "$TITLE" \
        --arg body "$BODY" \
        --arg branch "$BRANCH_NAME" \
        --arg task_dir "$TASK_DIR" \
        '{
            dry_run: true,
            title: $title,
            body: $body,
            branch: $branch,
            task_dir: $task_dir
        }'
    exit 0
fi

# Check git status
if [[ -z "$(git status --porcelain)" ]]; then
    echo '{"error": "no changes to commit"}' | jq .
    exit 1
fi

# Get current branch
CURRENT_BRANCH=$(git branch --show-current)
BASE_BRANCH=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')
BASE_BRANCH="${BASE_BRANCH:-main}"

# Create branch if needed
if [[ "$CURRENT_BRANCH" != "$BRANCH_NAME" ]]; then
    git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
fi

# Stage and commit
git add -A
git commit -m "$TITLE

Co-Authored-By: Claude <noreply@anthropic.com>" || true

# Push
git push -u origin "$BRANCH_NAME" 2>/dev/null || git push origin "$BRANCH_NAME"

# Create labels if needed
gh label create "siat" --color "0052CC" --force 2>/dev/null || true
gh label create "$TASK_ID" --color "FBCA04" --force 2>/dev/null || true

# Create PR with labels
PR_URL=$(gh pr create \
    --title "$TITLE" \
    --body "$BODY" \
    --base "$BASE_BRANCH" \
    --label "siat" \
    --label "$TASK_ID" \
    2>&1) || {
    # Retry without labels if something fails
    PR_URL=$(gh pr create \
        --title "$TITLE" \
        --body "$BODY" \
        --base "$BASE_BRANCH" \
        2>&1)
}

PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]*$')

# Update implement spec with PR link
if [[ -n "$PR_NUMBER" ]]; then
    # Add github_pr field after first --- in frontmatter
    # Use awk for cross-platform compatibility
    awk -v pr_url="$PR_URL" '
        NR==1 && /^---$/ { print; print "github_pr: \"" pr_url "\""; next }
        { print }
    ' "$IMPLEMENT_SPEC" > "${IMPLEMENT_SPEC}.tmp" && mv "${IMPLEMENT_SPEC}.tmp" "$IMPLEMENT_SPEC"
fi

jq -n \
    --arg url "$PR_URL" \
    --arg number "$PR_NUMBER" \
    --arg title "$TITLE" \
    --arg branch "$BRANCH_NAME" \
    --arg task_dir "$TASK_DIR" \
    '{
        success: true,
        pr_url: $url,
        pr_number: $number,
        title: $title,
        branch: $branch,
        task_dir: $task_dir
    }'
