#!/bin/bash
# siat-gh-issue.sh - Create or update GitHub issue from spec document
# Deterministic issue creation with consistent formatting
#
# Usage: siat-gh-issue.sh <spec_path> [--dry-run] [--update]
# Flags:
#   --dry-run  Preview without creating/updating issue
#   --update   Update existing issue (requires github_issue in frontmatter)
# Output: JSON with issue URL or dry-run preview

set -e

# Parse arguments
SPEC_PATH=""
DRY_RUN=false
UPDATE_MODE=false

for arg in "$@"; do
    case $arg in
        --dry-run) DRY_RUN=true ;;
        --update) UPDATE_MODE=true ;;
        --remote) ;; # deprecated, ignored
        *) [[ -z "$SPEC_PATH" ]] && SPEC_PATH="$arg" ;;
    esac
done

# ============================================================================
# Helper Functions
# ============================================================================

slugify_to_title() {
    # task-id-name → Task Id Name
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

get_frontmatter_field() {
    local file="$1"
    local field="$2"

    awk -v field="$field" '
        /^---$/ { if (in_fm) exit; in_fm=1; next }
        in_fm && $0 ~ "^"field":" {
            gsub(/^[^:]+:[[:space:]]*/, "")
            gsub(/^"/, ""); gsub(/"$/, "")
            print
            exit
        }
    ' "$file"
}

get_section() {
    local file="$1"
    local header="$2"

    awk -v header="$header" '
        /^---$/ { if (!past_fm) { past_fm=1; next } }
        past_fm && $0 ~ "^##[[:space:]]+"header {
            in_section=1
            next
        }
        in_section && /^##[[:space:]]/ { exit }
        in_section { print }
    ' "$file" | sed '/^$/N;/^\n$/d'  # Remove consecutive blank lines
}

get_body_after_frontmatter() {
    local file="$1"
    awk '
        /^---$/ { if (in_fm) { in_fm=0; next } in_fm=1; next }
        !in_fm { print }
    ' "$file"
}

# ============================================================================
# Main Logic
# ============================================================================

if [[ ! -f "$SPEC_PATH" ]]; then
    echo '{"error": "spec file not found", "path": "'"$SPEC_PATH"'"}' | jq .
    exit 1
fi

# Extract metadata
TASK_ID=$(get_frontmatter_field "$SPEC_PATH" "id")
STEP=$(basename "$SPEC_PATH" .md)

# Generate title
TITLE=$(slugify_to_title "$TASK_ID")
TITLE="[${STEP}] ${TITLE}"

# Get full spec content (after frontmatter)
FULL_SPEC=$(get_body_after_frontmatter "$SPEC_PATH")

# Build issue body
BODY="## Source
- Spec: \`${SPEC_PATH}\`
- Task ID: \`${TASK_ID}\`
- Step: \`${STEP}\`

---

<details>
<summary>📄 <strong>Full Spec Document</strong> (click to expand)</summary>

${FULL_SPEC}

</details>

---
*Generated by siat workflow*"

# Labels: siat (workflow), step name, task_id
LABELS=("siat" "$STEP" "$TASK_ID")

# Create labels if they don't exist (silently ignore if already exists)
for label in "${LABELS[@]}"; do
    # Use different colors for different label types
    case "$label" in
        siat)      COLOR="0052CC" ;;  # Blue - workflow identifier
        specify)   COLOR="7057FF" ;;  # Purple - spec step
        plan)      COLOR="008672" ;;  # Teal - plan step
        implement) COLOR="D93F0B" ;;  # Orange - implement step
        review)    COLOR="0E8A16" ;;  # Green - review step
        *)         COLOR="FBCA04" ;;  # Yellow - task_id or other
    esac
    gh label create "$label" --color "$COLOR" --force 2>/dev/null || true
done

# ============================================================================
# Update Mode: Update existing issue
# ============================================================================

if [[ "$UPDATE_MODE" == "true" ]]; then
    # Get existing issue URL from frontmatter
    EXISTING_ISSUE_URL=$(get_frontmatter_field "$SPEC_PATH" "github_issue")

    if [[ -z "$EXISTING_ISSUE_URL" ]]; then
        echo '{"error": "no github_issue found in frontmatter for update", "path": "'"$SPEC_PATH"'"}' | jq .
        exit 1
    fi

    ISSUE_NUMBER=$(echo "$EXISTING_ISSUE_URL" | grep -oE '[0-9]+$')

    if [[ "$DRY_RUN" == "true" ]]; then
        LABELS_STR=$(IFS=','; echo "${LABELS[*]}")
        jq -n \
            --arg title "$TITLE" \
            --arg body "$BODY" \
            --arg labels "$LABELS_STR" \
            --arg spec_path "$SPEC_PATH" \
            --arg issue_number "$ISSUE_NUMBER" \
            --arg issue_url "$EXISTING_ISSUE_URL" \
            '{
                dry_run: true,
                mode: "update",
                title: $title,
                body: $body,
                labels: $labels,
                spec_path: $spec_path,
                issue_number: $issue_number,
                issue_url: $issue_url
            }'
        exit 0
    fi

    # Update issue body
    gh issue edit "$ISSUE_NUMBER" --body "$BODY" 2>/dev/null || {
        echo '{"error": "failed to update issue", "issue_number": "'"$ISSUE_NUMBER"'"}' | jq .
        exit 1
    }

    # Add update comment
    UPDATE_COMMENT="## Updated

Spec document has been updated after feedback.

**Updated at**: $(date '+%Y-%m-%d %H:%M:%S')

---
*Please review the updated spec in the issue body above.*"

    gh issue comment "$ISSUE_NUMBER" --body "$UPDATE_COMMENT" 2>/dev/null || true

    jq -n \
        --arg url "$EXISTING_ISSUE_URL" \
        --arg number "$ISSUE_NUMBER" \
        --arg title "$TITLE" \
        --arg spec_path "$SPEC_PATH" \
        '{
            success: true,
            mode: "update",
            issue_url: $url,
            issue_number: $number,
            title: $title,
            spec_path: $spec_path
        }'
    exit 0
fi

# ============================================================================
# Create Mode: Create new issue
# ============================================================================

if [[ "$DRY_RUN" == "true" ]]; then
    LABELS_STR=$(IFS=','; echo "${LABELS[*]}")
    jq -n \
        --arg title "$TITLE" \
        --arg body "$BODY" \
        --arg labels "$LABELS_STR" \
        --arg spec_path "$SPEC_PATH" \
        '{
            dry_run: true,
            mode: "create",
            title: $title,
            body: $body,
            labels: $labels,
            spec_path: $spec_path
        }'
    exit 0
fi

# Build label arguments
LABEL_ARGS=()
for label in "${LABELS[@]}"; do
    LABEL_ARGS+=(--label "$label")
done

# Create issue with all labels
ISSUE_URL=$(gh issue create \
    --title "$TITLE" \
    --body "$BODY" \
    "${LABEL_ARGS[@]}" \
    2>&1) || {
    # Retry without labels if something fails
    ISSUE_URL=$(gh issue create \
        --title "$TITLE" \
        --body "$BODY" \
        2>&1)
}

ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -o '[0-9]*$')

# Append issue link to spec
if [[ -n "$ISSUE_NUMBER" ]]; then
    # Add github_issue field after first --- in frontmatter
    # Use awk for cross-platform compatibility
    awk -v issue_url="$ISSUE_URL" '
        NR==1 && /^---$/ { print; print "github_issue: \"" issue_url "\""; next }
        { print }
    ' "$SPEC_PATH" > "${SPEC_PATH}.tmp" && mv "${SPEC_PATH}.tmp" "$SPEC_PATH"
fi

jq -n \
    --arg url "$ISSUE_URL" \
    --arg number "$ISSUE_NUMBER" \
    --arg title "$TITLE" \
    --arg spec_path "$SPEC_PATH" \
    '{
        success: true,
        mode: "create",
        issue_url: $url,
        issue_number: $number,
        title: $title,
        spec_path: $spec_path
    }'
